version: '2.2'

services:
  api:
    image: back-habit-app
    build: .
    ports:
      - "4005:4005"
    restart: on-failure
    container_name: back-habit-app
    command: npm run start
    volumes:
      - .:/app
      - /app/node_modules
