version: '2.2'

services:
  api:
    image: habit-back
    build: .
    ports:
      - "4005:4005"
    restart: on-failure
    container_name: habit-back
    volumes:
      - .:/app
      - /app/node_modules
      - .env
      - 
